In [2]:
import numpy as np

arr = np7.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
# l'array si crea a partire da una lista
list_for_array = [1, 2, 3, 4, 5]
print(type(list_for_array))
arr = np.array(list_for_array)
print(type(arr))


<class 'list'>
<class 'numpy.ndarray'>


In [4]:
# a cosa serve ndmin: dimensione dell'array
arr = np.array([1, 2, 3, 4, 5, 6], ndmin=1)
print(arr)

lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista3 = [lista1, lista2]

arr = np.array(lista3, ndmin=2)
print(arr)

arr = np.array(42, ndmin=0)
print(arr)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
42


In [5]:
arr = np.array([1, 2, 3, 4])
# primo elemento
print(arr[0])

# ultimo elemento
print(arr[3])
print(arr[-1])


1
4
4


In [6]:
# creare un array vuoto
# (non normale in Python)
# e in un secondo momento inserire i valori

# array di numpy.float64
array_vuoto = np.zeros(5)
print(array_vuoto)

print(array_vuoto[0])
print(type(array_vuoto[0]))

float_number = 0.0
print(type(float_number))

# array di numpy.int64
array_vuoto = np.zeros(5, dtype=int)
print(type(array_vuoto[0]))

[0. 0. 0. 0. 0.]
0.0
<class 'numpy.float64'>
<class 'float'>
<class 'numpy.int64'>


In [7]:
dim = 5
array_vuoto = np.zeros(dim, dtype=int)
print(array_vuoto)

# inserire la temperatura degli ultimi 5 giorni
# indice 0 e la temperatura meno recente
# indice 4 e la temperatura piu recente
array_vuoto[0] = 19
array_vuoto[1] = 21
array_vuoto[2] = 23
array_vuoto[3] = 24
array_vuoto[4] = 25

print(array_vuoto)

[0 0 0 0 0]
[19 21 23 24 25]


In [8]:
dim = 5
array_vuoto = np.zeros(dim, dtype=int)
print(array_vuoto)

# inserire la temperatura degli ultimi 5 giorni
# indice 0 e la temperatura meno recente
# indice 4 e la temperatura piu recente
for i in range(5): # [0, 1, 2, 3, 4]
    value = int(input("inserisci la temperatura"))
    array_vuoto[i] = value

print(array_vuoto)

[0 0 0 0 0]
[2 3 4 5 6]


In [9]:
lista = []

# inserire la temperatura degli ultimi 5 giorni
# indice 0 e la temperatura meno recente
# indice 4 e la temperatura piu recente
for i in range(5): # [0, 1, 2, 3, 4]
    value = int(input("inserisci la temperatura"))
    lista.append(value)

dim = len(lista)
array_vuoto = np.array(lista)

print(array_vuoto)

[7 8 9 5 6]


In [11]:
# aggionare/modificare un array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# al posto 3 voglio 100
arr[2] = 100
print(arr)


[1 2 3 4 5]
[  1   2 100   4   5]


In [12]:
# aggiungere un nuovo elemento all'array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# voglio farlo diventare [1, 2, 3, 4, 5, 6]
# non si puo fare

# devo creare un nuovo array con 6 elementi


NameError: name 'numpy' is not defined

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[1:5:2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[2 4]


In [ ]:
import numpy as np

# creare un vettore vuoto (tutti 0)
def crea_vettore(dimensione) -> np.ndarray:
    vettore = np.zeros(dimensione, dtype=np.int8)
    return vettore

dimensione_del_vettore = 4
vettore = crea_vettore(dimensione_del_vettore)
print(vettore)
print(type(vettore[0]))

# inserimento di elemento
def inserisci_elemento(
        vettore: np.ndarray, 
        elemento: int,
        posizione: int
        ) -> np.ndarray:
    vettore[posizione] = elemento
    return vettore

elemento = 3
posizione = 1
vettore_aggiornato = inserisci_elemento(vettore, elemento, posizione)
print(vettore)


# inserimento tutti gli elementi
import random
for i in range(dimensione_del_vettore):
    elemento = random.randint(1,10)
    vettore_aggiornato = inserisci_elemento(vettore, elemento, i)
print(vettore)


# elimina un elemento
def elimina_elemento(
        vettore: np.ndarray, 
        posizione: int
        ) -> np.ndarray:
    vettore[posizione] = 0
    return vettore

posizione = 1
vettore_aggiornato = elimina_elemento(vettore, posizione)
print(vettore)

# ordinare il vettore 
# semplifico: trova il minimo del vettore
def trova_minimo(vettore: np.ndarray) -> int:
    minimo = vettore[0]
    for i in range(len(vettore)):
        if vettore[i] < minimo:
            minimo = vettore[i]
    return minimo

# no: trova la posizione del minimo del vettore
def trova_posizione_minimo(vettore: np.ndarray) -> int:
    minimo = vettore[0]
    posizione_minimo = 0
    for i in range(len(vettore)):
        if vettore[i] < minimo:
            minimo = vettore[i]
            posizione_minimo = i
    return posizione_minimo

# semplifico: scambia posizione recente con la posizione del minimo
def scambia_posizioni(
        vettore: np.ndarray, 
        posizione_minimo: int,
        posizione_recente: int) -> int:
    temp = vettore[posizione_recente]
    vettore[posizione_recente] = vettore[posizione_minimo]
    vettore[posizione_minimo] = temp
    return vettore
    
print(vettore)
posizione_minimo = trova_posizione_minimo(vettore)
vettore = scambia_posizioni(vettore,posizione_minimo,0)
print(vettore)
