In [23]:
import numpy as np

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [24]:
# l'array si crea a partire da una lista
list_for_array = [1, 2, 3, 4, 5]
print(type(list_for_array))
arr = np.array(list_for_array)
print(type(arr))


<class 'list'>
<class 'numpy.ndarray'>


In [17]:
# a cosa serve ndmin: dimensione dell'array
arr = np.array([1, 2, 3, 4, 5, 6], ndmin=1)
print(arr)

lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista3 = [lista1, lista2]

arr = np.array(lista3, ndmin=2)
print(arr)

arr = np.array(42, ndmin=0)
print(arr)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
42


In [22]:
arr = np.array([1, 2, 3, 4])
# primo elemento
print(arr[0])

# ultimo elemento
print(arr[3])
print(arr[-1])


1
4
4


In [32]:
# creare un array vuoto
# (non normale in Python)
# e in un secondo momento inserire i valori

# array di numpy.float64
array_vuoto = np.zeros(5)
print(array_vuoto)

print(array_vuoto[0])
print(type(array_vuoto[0]))

float_number = 0.0
print(type(float_number))

# array di numpy.int64
array_vuoto = np.zeros(5, dtype=int)
print(type(array_vuoto[0]))

[0. 0. 0. 0. 0.]
0.0
<class 'numpy.float64'>
<class 'float'>
<class 'numpy.int64'>


In [34]:
dim = 5
array_vuoto = np.zeros(dim, dtype=int)
print(array_vuoto)

# inserire la temperatura degli ultimi 5 giorni
# indice 0 e la temperatura meno recente
# indice 4 e la temperatura piu recente
array_vuoto[0] = 19
array_vuoto[1] = 21
array_vuoto[2] = 23
array_vuoto[3] = 24
array_vuoto[4] = 25

print(array_vuoto)

[0 0 0 0 0]
[19 21 23 24 25]


In [43]:
dim = 5
array_vuoto = np.zeros(dim, dtype=int)
print(array_vuoto)

# inserire la temperatura degli ultimi 5 giorni
# indice 0 e la temperatura meno recente
# indice 4 e la temperatura piu recente
for i in range(5): # [0, 1, 2, 3, 4]
    value = int(input("inserisci la temperatura"))
    array_vuoto[i] = value

print(array_vuoto)

[0 0 0 0 0]
[1 2 3 4 5]


In [45]:
lista = []

# inserire la temperatura degli ultimi 5 giorni
# indice 0 e la temperatura meno recente
# indice 4 e la temperatura piu recente
for i in range(5): # [0, 1, 2, 3, 4]
    value = int(input("inserisci la temperatura"))
    lista.append(value)

dim = len(lista)
array_vuoto = np.array(lista)

print(array_vuoto)

[1 2 3 4 5]


In [47]:
# aggionare/modificare un array
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

# al posto 3 voglio 100
arr[2] = 100
print(arr)


[1 2 3 4 5]
[  1   2 100   4   5]


In [48]:
# aggiungere un nuovo elemento all'array
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

# voglio farlo diventare [1, 2, 3, 4, 5, 6]
# non si puo fare

# devo creare un nuovo array con 6 elementi


[1 2 3 4 5]


In [53]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[1:5:2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[2 4]
