In [1]:
import numpy as np

# ordinare il vettore 


# semplifico: trova il minimo del vettore
def trova_minimo(vettore: np.ndarray) -> int:
    minimo = vettore[0]
    for i in range(len(vettore)):
        if vettore[i] < minimo:
            minimo = vettore[i]
    return minimo

# no: trova la posizione del minimo del vettore
def trova_posizione_minimo(vettore: np.ndarray) -> int:
    minimo = vettore[0]
    posizione_minimo = 0
    for i in range(len(vettore)):
        if vettore[i] < minimo:
            minimo = vettore[i]
            posizione_minimo = i
    return posizione_minimo

# semplifico: scambia posizione recente con la posizione del minimo
def scambia_posizioni(
        vettore: np.ndarray, 
        posizione_minimo: int,
        posizione_recente: int) -> int:
    temp = vettore[posizione_recente]
    vettore[posizione_recente] = vettore[posizione_minimo]
    vettore[posizione_minimo] = temp
    return vettore

lista = [5, 3, 2, 4, 1]
vettore = np.array(lista)

print(vettore)
posizione_minimo = trova_posizione_minimo(vettore)
vettore = scambia_posizioni(vettore,posizione_minimo,0)
print(vettore)
# da finire ...


[5 3 2 4 1]
[1 3 2 4 5]


In [4]:
def selection_sort(lst):
    n = len(lst)
    for i in range(n - 1):
        min_index = find_min(lst, i, n)
        swap_elements(lst, i, min_index)

def find_min(lst, start, end):
    min_index = start
    for j in range(start + 1, end):
        if lst[j] < lst[min_index]:
            min_index = j
    return min_index

def swap_elements(lst, i, j):
    lst[i], lst[j] = lst[j], lst[i]
    
lista = [5, 3, 2, 4, 1]
vettore = np.array(lista)
print(vettore)
selection_sort(vettore)
print(vettore)


[5 3 2 4 1]
[1 2 3 4 5]
